language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
before_install:
install:
  - npm install -g codecov
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov