language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
env:
  - TRAVIS=true
before_install:
install:
  - npm install
  - npm install -i codecov
script:
  - npm run lint
  - npm run coverage
  - codecov